version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "personal"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    open-pull-requests-limit: 0
